### ISSUE TITLE
Lokalní verze

### ISSUE THREAD

**Issue by MikkCZ** [FHRNet/BakalariMagicActions#6]
Nešlo by to vlastně udělat úplně lokálně přímo v prohlížeči pomocí https://addons.mozilla.org/cs/firefox/addon/greasemonkey/ nebo https://addons.mozilla.org/cs/firefox/addon/scriptish/? Pro Chrome určitě také takový doplněk bude.

**Comment by FHRNet** [comment]
Samozřejmě, že by to šlo - pár takových uživatelů mám. Jenže je to nepohodlné a pro velkou většinu "moc složité". Navíc téměř 60% přístupů je z mobilních zařízení a mobilní prohlížeče (kromě Firefoxu) addony/extensions neumí.

**Comment by vojta001** [comment]
Navíc extension nevypadá moc důvěryhodně. Osobně bych se zdráhal přidat si do prohlížeče rozšíření, které potřebuje přístup k čtení o pozměňování stránek, jež navštívím.

**Comment by FHRNet** [comment]
Popravdě řečeno, přihlašování a obecně přístup na stránky přes (nejen reverzní) proxy servery třetí strany také není úplně nejdůvěryhodnější - bylo by velmi snadné přidávat do stránek nějaký malicious kód, popřípadě zaznamenávat obsah komunikace.On Feb 2, 2017 21:18, vojta001 <notifications@github.com> wrote:Navíc extension nevypadá moc důvěryhodně. Osobně bych se zdráhal přidat si do prohlížeče rozšíření, které potřebuje přístup k čtení o pozměňování stránek, jež navštívím.

**Comment by vojta001** [comment]
To samozřejmě, ale zcela jasně vím, že maximum, co můžeš udělat je ukradnout mi přihlašovací údaje k Bakalářům (což je sice nepěkné, ale ne smrtelné) a možná tak u mě pustit nějaký JS (provádět DoS, případně útočit na stránky nezabezpečené proti CSRF).
