### ISSUE TITLE
listen in bakalari.conf

### ISSUE THREAD

**Issue by vojta001** [FHRNet/BakalariMagicActions#7]
I noticed when trying to make it work on nginx/1.10.3 (Ubuntu), that these lines

https://github.com/FHRNet/BakalariMagicActions/blob/bebaeb44b3e5a144f3c34d0ba2b7f4c749594c87/bakalari.conf#L12
https://github.com/FHRNet/BakalariMagicActions/blob/bebaeb44b3e5a144f3c34d0ba2b7f4c749594c87/bakalari.conf#L26
instruct Nginx to listen on IPv6 only. Is it intended or has the syntax changed since it was written?

**Comment by FHRNet** [comment]
Working as intended. You should have a `default.conf` in your `conf.d` directory, which tells nginx what to do in case the hostname is not recognized and on what addresses to listen.  

Mine `default.conf`:  
  

```
server {
    listen [::]:80 default_server ipv6only=off;
    listen [::]:443 ssl default_server ipv6only=off http2;

    ssl_certificate /var/www/default/ssl/default.crt;
    ssl_certificate_key /var/www/default/ssl/default.key;


    access_log /var/log/nginx/default.access.log main;
    error_log /var/log/nginx/default.error.log;

    location = /404.html {
        root /var/www/html;
    }

    error_page 404 /404.html;

    try_files $uri =404;
}
```  
  
See the `ipv6only=off` there? This option has to be in just one file, else nginx will complain.  
So you should have this default file and then  
```
listen [::]:80; 
listen [::]:443 ssl http2;
```
  

in ever server block where you want to accept connections from these ports.
